### ISSUE TITLE
Dark empty screen on Streams page (v2)

### ISSUE THREAD

**Issue by dmk1111** [Mo45/STSU-Web#1]
When I navigate to [Streams v2](https://uk.gametranslation.net/twitch.php) page, this is what I see after I press Play button:
![image](https://user-images.githubusercontent.com/11341287/48344819-d6dee600-e67e-11e8-8f3f-c0e6dc615810.png)

I'd suggest adding autoplay for first available stream or some next steps, as it is not obvious, that user has to select stream after he already pressed Play on main screen.

**Comment by Mo45** [comment]
There is one problem. Most of the time, all streams are offline.

**Comment by dmk1111** [comment]
Could we detect is any stream is online? Or maybe we can just don't let user press `Play` in case all streams are offline

**Comment by Mo45** [comment]
Streams V2 page is abandoned.
